name: flutter_food_order
description: Food Ordering App Built in Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_crashlytics: ^2.8.2

  flutter_native_splash: ^2.2.3+1
  provider: ^5.0.0-nullsafety.1
  lottie: ^1.3.0
  shared_preferences: ^2.0.15
  injector: ^2.0.0
  copy_with_extension: ^4.0.2
  geolocator: ^9.0.0
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  copy_with_extension_gen: ^4.0.2

flutter:

  uses-material-design: true
  assets:
    - res/images/
    - res/fonts/
    - res/anim/

  fonts:
    - family: Abel
      fonts:
        - asset: res/fonts/abel/Abel-Regular.ttf
    - family: Sofia
      fonts:
        - asset: res/fonts/sofia/Sofia-Regular.otf
        - asset: res/fonts/sofia/Sofia-Bold.ttf
          weight: 600
        - asset: res/fonts/sofia/Sofia-Light.otf
          weight: 300

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/images/logo_ayomaem.png"

flutter_native_splash:
  color: "#FE724C"
  image: res/images/logo_ayomaem.png